### ISSUE TITLE
Błędy podczas dodawania wydarzenia

### ISSUE THREAD

**Issue by Igifigi** [Igifigi/protonApp#16]

**Comment by Igifigi** [comment]
![Zrzut ekranu 2022-04-21 112644](https://user-images.githubusercontent.com/44808028/164428900-5089326a-d63e-4e29-8db0-8cb626d7be4d.png)
![Zrzut ekranu 2022-04-21 113048](https://user-images.githubusercontent.com/44808028/164428903-b5003bb2-ea19-4849-8e30-61bc6d8b7858.png)
![Zrzut ekranu 2022-04-21 113106](https://user-images.githubusercontent.com/44808028/164428906-a0d225c5-cdc4-48ca-b94d-25674c0dc919.png)
![Zrzut ekranu 2022-04-21 113119](https://user-images.githubusercontent.com/44808028/164428909-45487edc-95a5-4c32-a59e-fe25b0e1c103.png)

**Comment by Eastkill** [comment]
Naprawione (format daty w c# i sql jest różny, wystarczyło przekonwertować)
